export function szam(n) {
  if (n === 1) return 'egy'
  if (n === 2) return 'kettő'
  if (n === 3) return 'három'
  if (n === 4) return 'négy'
  if (n === 5) return 'öt'
  if (n === 6) return 'hat'
  if (n === 7) return 'hét'
  if (n === 8) return 'nyolc'
  if (n === 9) return 'kilenc'
  if (n === 10) return 'tíz'
  if (n === 21) return 'huszonegy'
  if (n === 22) return 'huszonkettő'
  if (n === 23) return 'huszonhárom'
  if (n === 24) return 'huszonnégy'
  if (n === 25) return 'huszonöt'
  if (n === 26) return 'huszonhat'
  if (n === 27) return 'huszonhét'
  if (n === 28) return 'huszonnyolc'
  if (n === 29) return 'huszonkilenc'
  if (n === 30) return 'harminc'
}
